"""Build data/pok_map.js: a simplified Plane of Knowledge minimap with the
12 turn-in NPC positions, from a Brewall-format EQ map file.

EQ map file records: "L a1, b1, z1, a2, b2, z2, r, g, b" where a = -X(game)
and b = -Y(game); drawn directly in SVG this puts north up and east right.
Calibrated against the library footprint (the only high-z structure) and
the zone-stone labels (Halas north, Neriak south). NPC spawns below use the
(Y, X) convention as printed by pqdi.cc, so map_x = -X, map_y = -Y.

Usage: python tools/build_pok_map.py <poknowledge.txt> [labels.txt]
"""
import json
import re
import sys
from pathlib import Path

SRC = Path(sys.argv[1])
LABELS_SRC = Path(sys.argv[2]) if len(sys.argv) > 2 else None
OUT = Path(__file__).resolve().parent.parent / "data" / "pok_map.js"

# (game Y, game X) from pqdi.cc + a short "which floor" hint for the runner.
NPCS = {
    "Vicar Ceraen": (114, 931, "Library, 1 floor down: balcony right of the entrance"),
    "Wanderer Astobin": (8, 1067, "Library, ground floor, south side"),
    "Illusionist Jerup": (2, 1074, "Library, 2 floors down from the entrance"),
    "Elementalist Somat": (56, 1106, "Library, 2nd floor, northwest side"),
    "Heretic Drahur": (56, 789, "Library, bottom basement, northeast nook"),
    "Cavalier Waut": (89, 1046, "Library, upper floor (next to top)"),
    "Pathfinder Viliken": (-22, 922, "Library, 3rd floor"),
    "Reaver Nydlil": (-84, 762, "Library, bottom basement, southeast nook"),
    "Mystic Abomin": (76, 980, "Library, ground floor"),
    "Channeler Olaemos": (-64, 916, "Library, 2 floors down (basement)"),
    "Primalist Saosith": (9, 1110, "Library, top floor"),
    "Minstrel Eoweril": (93, 847, "Library, 2 floors down (basement)"),
}

MIN_SEG = 12       # drop segments shorter than this (map units)
MAX_SEGS = 3500    # raise the threshold until we fit under this many

segs = []
high = []  # segments above ground level: the library floors
line_re = re.compile(
    r"^L\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+)")
for raw in SRC.read_text(encoding="utf-8", errors="replace").splitlines():
    m = line_re.match(raw)
    if m:
        x1, y1, z1, x2, y2, z2 = (float(v) for v in m.groups())
        segs.append((round(x1), round(y1), round(x2), round(y2)))
        if z1 > 20 and z2 > 20:
            high.append((x1, y1, x2, y2))

min_seg = MIN_SEG
kept = segs
while True:
    kept = [s for s in segs if (s[0] - s[2]) ** 2 + (s[1] - s[3]) ** 2 >= min_seg ** 2]
    if len(kept) <= MAX_SEGS:
        break
    min_seg += 4
print(f"segments: {len(segs)} -> {len(kept)} (min length {min_seg})")

xs = [v for s in kept for v in (s[0], s[2])]
ys = [v for s in kept for v in (s[1], s[3])]
bounds = [min(xs), min(ys), max(xs), max(ys)]
extent = max(bounds[2] - bounds[0], bounds[3] - bounds[1])
stroke = max(2, round(extent / 240))

# Chain segments into one path string, reusing the pen position when possible.
d_parts = []
cx = cy = None
for x1, y1, x2, y2 in kept:
    if (x1, y1) != (cx, cy):
        d_parts.append(f"M{x1} {y1}")
    d_parts.append(f"L{x2} {y2}")
    cx, cy = x2, y2
path_d = "".join(d_parts)

# Orientation labels: the banks (from the labels layer) and a synthetic
# "Library" label under the building footprint found via the high-z pass.
labels = []
if LABELS_SRC and LABELS_SRC.is_file():
    p_re = re.compile(r"^P\s*(-?[\d.]+),\s*(-?[\d.]+),\s*-?[\d.]+,\s*\d+,\s*\d+,\s*\d+,\s*\d+,\s*(.+)$")
    for raw in LABELS_SRC.read_text(encoding="utf-8", errors="replace").splitlines():
        m = p_re.match(raw)
        if not m:
            continue
        text = m.group(3).replace("_", " ").strip()
        if "Banker" not in text:
            continue
        x, y = round(float(m.group(1))), round(float(m.group(2)))
        if all((x - l["x"]) ** 2 + (y - l["y"]) ** 2 > 150 ** 2 for l in labels):
            labels.append({"x": x, "y": y, "t": "Bank"})
if high:
    hx = [v for s in high for v in (s[0], s[2])]
    hy = [v for s in high for v in (s[1], s[3])]
    labels.append({"x": round((min(hx) + max(hx)) / 2), "y": round(max(hy) + 90), "t": "Library"})
print(f"labels kept: {[(l['t'], l['x'], l['y']) for l in labels]}")

data = {
    "bounds": bounds,
    "stroke": stroke,
    "paths": [{"d": path_d, "c": "#3d4c66"}],
    "labels": labels,
    "npcs": {
        name: {"x": -x_game, "y": -y_game, "hint": hint}
        for name, (y_game, x_game, hint) in NPCS.items()
    },
}

# Sanity check: every marker must sit inside the map bounds.
for name, spot in data["npcs"].items():
    if not (bounds[0] <= spot["x"] <= bounds[2] and bounds[1] <= spot["y"] <= bounds[3]):
        print(f"WARNING: {name} marker outside map bounds: {spot}")

OUT.write_text(
    "// Plane of Knowledge minimap (generated by tools/build_pok_map.py from\n"
    "// Brewall's poknowledge map; NPC spawns from pqdi.cc).\n"
    "window.POK_MAP = " + json.dumps(data) + ";\n",
    encoding="utf-8")
print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB), bounds {bounds}, stroke {stroke}")
